In [1]:
import numpy as np
import pandas as pd
import glob
import string

from sklearn.model_selection import train_test_split
from nltk.tag import pos_tag

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
all_data = pd.DataFrame()
for f in glob.glob("./data/*.csv"):
    df = pd.read_csv(f)
    all_data = all_data.append(df,ignore_index=True)

In [3]:
all_data = all_data.sample(frac=1).reset_index(drop=True)

In [4]:
all_data['ff_ratio'] = (all_data.followers_count + 1) / (all_data.friends_count+1)
all_data['ff_ratio'] = all_data['ff_ratio'].round(decimals = 4)

In [28]:
list(all_data)

['id',
 'id_str',
 'screen_name',
 'location',
 'description',
 'url',
 'followers_count',
 'friends_count',
 'listedcount',
 'created_at',
 'favourites_count',
 'verified',
 'statuses_count',
 'lang',
 'status',
 'default_profile',
 'default_profile_image',
 'has_extended_profile',
 'name',
 'bot',
 'ff_ratio']

In [ ]:
all_data['acc_age'] =   - 
all_data['created_at'] = all_data['created_at']

In [5]:
train, test = train_test_split(all_data, test_size = 0.2)

In [6]:
train.shape , test.shape

((1785, 21), (447, 21))

In [16]:
train['ff_ratio'].describe()
bad_indices = np.where(np.isinf(train['ff_ratio']))
print bad_indices

(array([], dtype=int64),)


In [25]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier,export_graphviz
from sklearn import tree
clf = DecisionTreeClassifier(random_state=0,max_depth = 4)
train.has_extended_profile.fillna(False)
features = ['friends_count','followers_count','listedcount','favourites_count','verified','statuses_count','default_profile','default_profile_image','ff_ratio']
X = train[features]
y = train['bot']
clf.fit(X,y)
cross_val_score(clf, test[features], test['bot'], cv=10)

array([ 0.73333333,  0.8       ,  0.77777778,  0.84444444,  0.8       ,
        0.88888889,  0.82222222,  0.91111111,  0.79545455,  0.76744186])

In [15]:
cross_val_score(clf, train[features], train['bot'], cv=10)

array([ 0.81005587,  0.8547486 ,  0.86592179,  0.8603352 ,  0.87150838,
        0.89385475,  0.91061453,  0.84831461,  0.88700565,  0.81355932])

In [10]:
def visualize_tree(tree, feature_names):
    """Create tree png using graphviz.

    Args
    ----
    tree -- scikit-learn DecsisionTree.
    feature_names -- list of feature names.
    """
    with open("dt.dot", 'w') as f:
        export_graphviz(tree, out_file=f,
                        feature_names=feature_names)

    command = ["dot", "-Tpng", "dt.dot", "-o", "dt.png"]
    try:
        subprocess.check_call(command)
    except:
        exit("Could not run dot, ie graphviz, to "
             "produce visualization")

In [ ]:
visualize_tree(clf, features)

# Random Forest

In [24]:
from sklearn.ensemble import RandomForestClassifier
rdf = RandomForestClassifier(n_jobs=2 , max_depth = 6)
rdf.fit(X,y)
cross_val_score(rdf, test[features], test['bot'], cv=10)

array([ 0.88888889,  0.86666667,  0.93333333,  0.95555556,  0.86666667,
        0.91111111,  0.86666667,  0.88888889,  0.90909091,  0.90697674])

In [22]:
cross_val_score(clf, train[features], train['bot'], cv=10)

array([ 0.81005587,  0.8547486 ,  0.86592179,  0.8603352 ,  0.87150838,
        0.89385475,  0.91061453,  0.84831461,  0.88700565,  0.81355932])